CREATE TABLE tblbooks (
	bookid		int				not null,
	title		varchar(50)		not null,
	author		varchar(50)		not null,
	genre		varchar(50)		not null,
	price		varchar(5)		not null,
	description	varchar(750)		not null,
	image		varchar(100)	not null,
	primary key (bookid));
	
INSERT INTO tblbooks VALUES
	(1, "An Absolutely Remarkable Thing", 'Hank Green', 'Fiction', '$20', 'Roaming through New York City at three a.m., twenty-three-year-old April May stumbles across a giant sculpture. Delighted by its appearance and craftsmanship—like a ten-foot-tall Transformer wearing a suit of samurai armor—April and her best friend, Andy, make a video with it, which Andy uploads to YouTube. The next day, April wakes up to a viral video and a new life. News quickly spreads that there are Carls in dozens of cities around the world—from Beijing to Buenos Aires—and April, as their first documentarian, finds herself at the center of an intense international media spotlight.', 'https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book1.jpeg'),
	(2, 'Cilkas Journey', 'Heather Morris', 'Fiction', '$15', 'Cilka is just sixteen years old when she is taken to Auschwitz-Birkenau Concentration Camp in 1942, where the commandant immediately notices how beautiful she is. Forcibly separated from the other women prisoners, Cilka learns quickly that power, even unwillingly taken, equals survival.', 'https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book2.jpeg'),
	(3, 'The Midnight Library', 'Mike Haig', 'Fiction', '$17', 'Somewhere out beyond the edge of the universe there is a library that contains an infinite number of books, each one the story of another reality. One tells the story of your life as it is, along with another book for the other life you could have lived if you had made a different choice at any point in your life. While we all wonder how our lives might have been, what if you had the chance to go to the library and see for yourself? Would any of these other lives truly be better?','https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book3.jpeg');
	(4, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', '$15', 'The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraways interactions with mysterious millionaire Jay Gatsby and Gatsbys obsession to reunite with his former lover, Daisy Buchanan.', 'https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book4.jpeg'),
	(5, 'The Tattooist of Auschwitz', 'Heather Morris', 'Fiction', '$15', 'The Tattooist of Auschwitz is a 2018 Holocaust novel by New Zealand novelist Heather Morris. The book tells the story of how Slovakian Jew Lale Sokolov, who was imprisoned at Auschwitz in 1942, fell in love with a girl he was tattooing at the concentration camp', 'https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book5.jpeg'),
	(6, 'Becoming', 'Michelle Obama', 'Autobiography', '$20', 'In a life filled with meaning and accomplishment, Michelle Obama has emerged as one of the most iconic and compelling women of our era. As First Lady of the United States of America—the first African American to serve in that role—she helped create the most welcoming and inclusive White House in history, while also establishing herself as a powerful advocate for women and girls in the U.S. and around the world, dramatically changing the ways that families pursue healthier and more active lives, and standing with her husband as he led America through some of its most harrowing moments.', 'https://swe.umbc.edu/~srodrig1/bootstrap-5.3.0-alpha3-examples/carousel/book6.jpeg');